version: '3'

volumes:
  db_data:
  static_value:
  media_value:
  redoc:


services:

  db:
    image: postgres:13.10-alpine
    env_file: ./.env
    volumes:
      - db_data:/var/lib/postgresql/data/

  backend:
    image: mrsmile1812/food_backend:v.1.0
    env_file: ./.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db

  frontend:
    env_file: ./.env
    image: mrsmile1812/food_frontend:v.1.0
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    env_file: ./.env
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
