# Generated by Django 4.2.2 on 2023-07-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredientsinrecipes_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(help_text='Фотография блюда', upload_to='media/', verbose_name='Фотография'),
        ),
    ]
